# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "whisperfish-core/src/schema.rs"
patch_file = "whisperfish-core/src/schema.patch"
