Name:       harbour-whisperfish
Summary:    Signal client for SailfishOS
Version:    0.6.0
Release:    1
Group:      Qt/Qt
License:    GPL
# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}

URL:        https://github.com/monich/sailfish-barcode
Source0:    %{name}-%{version}.tar.bz2
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  desktop-file-utils

%description
Signal client for SailfishOS.

%prep
%setup -q -n %{name}-%{version}

%build
%qtc_qmake5 VERSION="%{version}"
%qtc_make %{?_smp_mflags}

%install
rm -rf %{buildroot}
install -p %(pwd)/harbour-whisperfish-message.conf %{buildroot}%{_datadir}/lipstick/notificationcategories/%{name}-message.conf
%qmake5_install

desktop-file-install --delete-original \
  --dir %{buildroot}%{_datadir}/applications \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/lipstick/notificationcategories/%{name}-message.conf
%{_datadir}/%{name}/qml
%{_datadir}/icons/hicolor/*/apps/
