var c=[//n=name,i=ISO,p=prefix -- see countries.js.md for source
{n:"Afghanistan",i:"AF",p:"+93"},
{n:"Åland Islands",i:"AX",p:"+358 18"},
{n:"Albania",i:"AL",p:"+355"},
{n:"Algeria",i:"DZ",p:"+213"},
{n:"American Samoa",i:"AS",p:"+1 684"},
{n:"Andorra",i:"AD",p:"+376"},
{n:"Angola",i:"AO",p:"+244"},
{n:"Anguilla",i:"AI",p:"+1 264"},
{n:"Antigua and Barbuda",i:"AG",p:"+1 268"},
{n:"Argentina",i:"AR",p:"+54"},
{n:"Armenia",i:"AM",p:"+374"},
{n:"Aruba",i:"AW",p:"+297"},
{n:"Ascension",i:"SH",p:"+247"},
{n:"Australia",i:"AU",p:"+61"},
{n:"Australian Antarctic Territory",i:"AQ",p:"+672 1"},
{n:"Australian External Territories",i:"",p:"+672"}, // NO ISO
{n:"Austria",i:"AT",p:"+43"},
{n:"Azerbaijan",i:"AZ",p:"+994"},
{n:"Bahamas",i:"BS",p:"+1 242"},
{n:"Bahrain",i:"BH",p:"+973"},
{n:"Bangladesh",i:"BD",p:"+880"},
{n:"Barbados",i:"BB",p:"+1 246"},
{n:"Barbuda",i:"AG",p:"+1 268"},
{n:"Belarus",i:"BY",p:"+375"},
{n:"Belgium",i:"BE",p:"+32"},
{n:"Belize",i:"BZ",p:"+501"},
{n:"Benin",i:"BJ",p:"+229"},
{n:"Bermuda",i:"BM",p:"+1 441"},
{n:"Bhutan",i:"BT",p:"+975"},
{n:"Bolivia",i:"BO",p:"+591"},
{n:"Bonaire",i:"BQ",p:"+599 7"},
{n:"Bosnia and Herzegovina",i:"BA",p:"+387"},
{n:"Botswana",i:"BW",p:"+267"},
{n:"Brazil",i:"BR",p:"+55"},
{n:"British Indian Ocean Territory",i:"IO",p:"+246"},
{n:"Brunei Darussalam",i:"BN",p:"+673"},
{n:"Bulgaria",i:"BG",p:"+359"},
{n:"Burkina Faso",i:"BF",p:"+226"},
{n:"Burundi",i:"BI",p:"+257"},
{n:"Cambodia",i:"KH",p:"+855"},
{n:"Cameroon",i:"CM",p:"+237"},
{n:"Canada",i:"CA",p:"+1"},
{n:"Cape Verde",i:"CV",p:"+238"},
{n:"Caribbean Netherlands",i:"",p:"+599 3"}, // NO ISO
{n:"Caribbean Netherlands",i:"",p:"+599 4"}, // NO ISO
{n:"Caribbean Netherlands",i:"",p:"+599 7"}, // NO ISO
{n:"Cayman Islands",i:"KY",p:"+1 345"},
{n:"Central African Republic",i:"CF",p:"+236"},
{n:"Chad",i:"TD",p:"+235"},
{n:"Chatham Island (New Zealand)",i:"NZ",p:"+64"},
{n:"Chile",i:"CL",p:"+56"},
{n:"China",i:"CN",p:"+86"},
{n:"Christmas Island",i:"CX",p:"+61 89164"},
{n:"Cocos (Keeling) Islands",i:"CC",p:"+61 89162"},
{n:"Colombia",i:"CO",p:"+57"},
{n:"Comoros",i:"KM",p:"+269"},
{n:"Congo (Democratic Republic of the)",i:"CD",p:"+243"},
{n:"Congo",i:"CG",p:"+242"},
{n:"Cook Islands",i:"CK",p:"+682"},
{n:"Costa Rica",i:"CR",p:"+506"},
{n:"Côte d'Ivoire",i:"CI",p:"+225"},
{n:"Croatia",i:"HR",p:"+385"},
{n:"Cuba",i:"CU",p:"+53"},
{n:"Curaçao",i:"CW",p:"+599 9"},
{n:"Cyprus",i:"CY",p:"+357"},
{n:"Czech Republic",i:"CZ",p:"+420"},
{n:"Denmark",i:"DK",p:"+45"},
{n:"Diego Garcia",i:"",p:"+246"}, // NO ISO, OCC. BY GB
{n:"Djibouti",i:"DJ",p:"+253"},
{n:"Dominica",i:"DM",p:"+1 767"},
{n:"Dominican Republic",i:"DO",p:"+1 809"},
{n:"Dominican Republic",i:"DO",p:"+1 829"},
{n:"Dominican Republic",i:"DO",p:"+1 849"},
{n:"Easter Island",i:"CL",p:"+56"},
{n:"Ecuador",i:"EC",p:"+593"},
{n:"Egypt",i:"EG",p:"+20"},
{n:"El Salvador",i:"SV",p:"+503"},
{n:"Equatorial Guinea",i:"GQ",p:"+240"},
{n:"Eritrea",i:"ER",p:"+291"},
{n:"Estonia",i:"EE",p:"+372"},
{n:"eSwatini",i:"SZ",p:"+268"},
{n:"Ethiopia",i:"ET",p:"+251"},
{n:"Falkland Islands (Malvinas)",i:"FK",p:"+500"},
{n:"Faroe Islands",i:"FO",p:"+298"},
{n:"Fiji",i:"FJ",p:"+679"},
{n:"Finland",i:"FI",p:"+358"},
{n:"France",i:"FR",p:"+33"},
{n:"French Antilles",i:"",p:"+596"}, // NO ISO
{n:"French Guiana",i:"GF",p:"+594"},
{n:"French Polynesia",i:"PF",p:"+689"},
{n:"Gabon",i:"GA",p:"+241"},
{n:"Gambia",i:"GM",p:"+220"},
{n:"Georgia",i:"GE",p:"+995"},
{n:"Germany",i:"DE",p:"+49"},
{n:"Ghana",i:"GH",p:"+233"},
{n:"Gibraltar",i:"GI",p:"+350"},
{n:"Greece",i:"GR",p:"+30"},
{n:"Greenland",i:"GL",p:"+299"},
{n:"Grenada",i:"GD",p:"+1 473"},
{n:"Guadeloupe",i:"GP",p:"+590"},
{n:"Guam",i:"GU",p:"+1 671"},
{n:"Guatemala",i:"GT",p:"+502"},
{n:"Guernsey",i:"GG",p:"+44 1481"},
{n:"Guernsey",i:"GG",p:"+44 7781"},
{n:"Guernsey",i:"GG",p:"+44 7839"},
{n:"Guernsey",i:"GG",p:"+44 7911"},
{n:"Guinea-Bissau",i:"GW",p:"+245"},
{n:"Guinea",i:"GN",p:"+224"},
{n:"Guyana",i:"GY",p:"+592"},
{n:"Haiti",i:"HT",p:"+509"},
{n:"Honduras",i:"HN",p:"+504"},
{n:"Hong Kong",i:"HK",p:"+852"},
{n:"Hungary",i:"HU",p:"+36"},
{n:"Iceland",i:"IS",p:"+354"},
{n:"India",i:"IN",p:"+91"},
{n:"Indonesia",i:"ID",p:"+62"},
{n:"Iran",i:"IR",p:"+98"},
{n:"Iraq",i:"IQ",p:"+964"},
{n:"Ireland",i:"IE",p:"+353"},
{n:"Isle of Man",i:"IM",p:"+44 1624"},
{n:"Isle of Man",i:"IM",p:"+44 7524"},
{n:"Isle of Man",i:"IM",p:"+44 7624"},
{n:"Isle of Man",i:"IM",p:"+44 7924"},
{n:"Israel",i:"IL",p:"+972"},
{n:"Italy",i:"IT",p:"+39"},
{n:"Jamaica",i:"JM",p:"+1 876"},
{n:"Jan Mayen",i:"SJ",p:"+47 79"},
{n:"Japan",i:"JP",p:"+81"},
{n:"Jersey",i:"JE",p:"+44 1534"},
{n:"Jordan",i:"JO",p:"+962"},
{n:"Kazakhstan",i:"KZ",p:"+7 6"},
{n:"Kazakhstan",i:"KZ",p:"+7 7"},
{n:"Kenya",i:"KE",p:"+254"},
{n:"Kiribati",i:"KI",p:"+686"},
{n:"Korea (North)",i:"KP",p:"+850"},
{n:"Korea (South)",i:"KR",p:"+82"},
{n:"Kosovo",i:"XK",p:"+383"}, // TEMP. CODE
{n:"Kuwait",i:"KW",p:"+965"},
{n:"Kyrgyzstan",i:"KG",p:"+996"},
{n:"Laos",i:"LA",p:"+856"},
{n:"Latvia",i:"LV",p:"+371"},
{n:"Lebanon",i:"LB",p:"+961"},
{n:"Lesotho",i:"LS",p:"+266"},
{n:"Liberia",i:"LR",p:"+231"},
{n:"Libya",i:"LY",p:"+218"},
{n:"Liechtenstein",i:"LI",p:"+423"},
{n:"Lithuania",i:"LT",p:"+370"},
{n:"Luxembourg",i:"LU",p:"+352"},
{n:"Macau (Macao)",i:"MO",p:"+853"},
{n:"Madagascar",i:"MG",p:"+261"},
{n:"Malawi",i:"MW",p:"+265"},
{n:"Malaysia",i:"MY",p:"+60"},
{n:"Maldives",i:"MV",p:"+960"},
{n:"Mali",i:"ML",p:"+223"},
{n:"Malta",i:"MT",p:"+356"},
{n:"Marshall Islands",i:"MH",p:"+692"},
{n:"Martinique",i:"MQ",p:"+596"},
{n:"Mauritania",i:"MR",p:"+222"},
{n:"Mauritius",i:"MU",p:"+230"},
{n:"Mayotte",i:"YT",p:"+262 269"},
{n:"Mayotte",i:"YT",p:"+262 639"},
{n:"Mexico",i:"MX",p:"+52"},
{n:"Micronesia (Federated States of)",i:"FM",p:"+691"},
{n:"Midway Island (USA)",i:"US",p:"+1 808"},
{n:"Moldova",i:"MD",p:"+373"},
{n:"Monaco",i:"MC",p:"+377"},
{n:"Mongolia",i:"MN",p:"+976"},
{n:"Montenegro",i:"ME",p:"+382"},
{n:"Montserrat",i:"MS",p:"+1 664"},
{n:"Morocco",i:"MA",p:"+212"},
{n:"Mozambique",i:"MZ",p:"+258"},
{n:"Myanmar",i:"MM",p:"+95"},
{n:"Nagorno-Karabakh",i:"AZ",p:"+374 47"}, // NO OWN ISO, DISPUTED
{n:"Nagorno-Karabakh",i:"AZ",p:"+374 97"}, // NO OWN ISO, DISPUTED
{n:"Namibia",i:"NA",p:"+264"},
{n:"Nauru",i:"NR",p:"+674"},
{n:"Nepal",i:"NP",p:"+977"},
{n:"Netherlands",i:"NL",p:"+31"},
{n:"Nevis",i:"KN",p:"+1 869"},
{n:"New Caledonia",i:"NC",p:"+687"},
{n:"New Zealand",i:"NZ",p:"+64"},
{n:"Nicaragua",i:"NI",p:"+505"},
{n:"Nigeria",i:"NG",p:"+234"},
{n:"Niger",i:"NE",p:"+227"},
{n:"Niue",i:"NU",p:"+683"},
{n:"Norfolk Island",i:"NF",p:"+672 3"},
{n:"Northern Cyprus",i:"CY",p:"+90 392"}, // OCC. BY TR
{n:"Northern Ireland",i:"GB",p:"+44 28"},
{n:"Northern Mariana Islands",i:"MP",p:"+1 670"},
{n:"North Macedonia",i:"MK",p:"+389"},
{n:"Norway",i:"NO",p:"+47"},
{n:"Oman",i:"OM",p:"+968"},
{n:"Pakistan",i:"PK",p:"+92"},
{n:"Palau",i:"PW",p:"+680"},
{n:"Palestine (State of)",i:"PS",p:"+970"},
{n:"Panama",i:"PA",p:"+507"},
{n:"Papua New Guinea",i:"PG",p:"+675"},
{n:"Paraguay",i:"PY",p:"+595"},
{n:"Peru",i:"PE",p:"+51"},
{n:"Philippines",i:"PH",p:"+63"},
{n:"Pitcairn Islands",i:"PN",p:"+64"},
{n:"Poland",i:"PL",p:"+48"},
{n:"Portugal",i:"PT",p:"+351"},
{n:"Puerto Rico",i:"PR",p:"+1 787"},
{n:"Puerto Rico",i:"PR",p:"+1 939"},
{n:"Qatar",i:"QA",p:"+974"},
{n:"Réunion",i:"RE",p:"+262"},
{n:"Romania",i:"RO",p:"+40"},
{n:"Russia",i:"RU",p:"+7"},
{n:"Rwanda",i:"RW",p:"+250"},
{n:"Saba",i:"BQ",p:"+599 4"},
{n:"Saint Barthélemy",i:"BL",p:"+590"},
{n:"Saint Helena",i:"SH",p:"+290"},
{n:"Saint Kitts and Nevis",i:"KN",p:"+1 869"},
{n:"Saint Lucia",i:"LC",p:"+1 758"},
{n:"Saint Martin (France)",i:"MF",p:"+590"},
{n:"Saint Pierre and Miquelon",i:"PM",p:"+508"},
{n:"Saint Vincent and the Grenadines",i:"VC",p:"+1 784"},
{n:"Samoa",i:"WS",p:"+685"},
{n:"San Marino",i:"SM",p:"+378"},
{n:"São Tomé and Príncipe",i:"ST",p:"+239"},
{n:"Saudi Arabia",i:"SA",p:"+966"},
{n:"Senegal",i:"SN",p:"+221"},
{n:"Serbia",i:"RS",p:"+381"},
{n:"Seychelles",i:"SC",p:"+248"},
{n:"Sierra Leone",i:"SL",p:"+232"},
{n:"Singapore",i:"SG",p:"+65"},
{n:"Sint Eustatius",i:"BQ",p:"+599 3"},
{n:"Sint Maarten (Netherlands)",i:"SX",p:"+1 721"},
{n:"Slovakia",i:"SK",p:"+421"},
{n:"Slovenia",i:"SI",p:"+386"},
{n:"Solomon Islands",i:"SB",p:"+677"},
{n:"Somalia",i:"SO",p:"+252"},
{n:"South Africa",i:"ZA",p:"+27"},
{n:"South Georgia and the South Sandwich Islands",i:"GS",p:"+500"},
{n:"South Ossetia",i:"GE",p:"+995 34"}, // NO OWN ISO, DISPUTED
{n:"South Sudan",i:"SS",p:"+211"},
{n:"Spain",i:"ES",p:"+34"},
{n:"Sri Lanka",i:"LK",p:"+94"},
{n:"Sudan",i:"SD",p:"+249"},
{n:"Suriname",i:"SR",p:"+597"},
{n:"Svalbard",i:"SJ",p:"+47 79"},
{n:"Sweden",i:"SE",p:"+46"},
{n:"Switzerland",i:"CH",p:"+41"},
{n:"Syria",i:"SY",p:"+963"},
{n:"Taiwan",i:"SJ",p:"+886"},
{n:"Tajikistan",i:"TJ",p:"+992"},
{n:"Tanzania",i:"TZ",p:"+255"},
{n:"Thailand",i:"TH",p:"+66"},
{n:"Timor-Leste",i:"TL",p:"+670"},
{n:"Togo",i:"TG",p:"+228"},
{n:"Tokelau",i:"TK",p:"+690"},
{n:"Tonga",i:"TO",p:"+676"},
{n:"Transnistria",i:"MD",p:"+373 2"},
{n:"Transnistria",i:"MD",p:"+373 5"},
{n:"Trinidad and Tobago",i:"TT",p:"+1 868"},
{n:"Tristan da Cunha",i:"SH",p:"+290 8"},
{n:"Tunisia",i:"TN",p:"+216"},
{n:"Turkey",i:"TR",p:"+90"},
{n:"Turkmenistan",i:"TM",p:"+993"},
{n:"Turks and Caicos Islands",i:"TC",p:"+1 649"},
{n:"Tuvalu",i:"TV",p:"+688"},
{n:"Uganda",i:"UG",p:"+256"},
{n:"Ukraine",i:"UA",p:"+380"},
{n:"United Arab Emirates",i:"AE",p:"+971"},
{n:"United Kingdom",i:"GB",p:"+44"},
{n:"United States",i:"US",p:"+1"},
{n:"Uruguay",i:"UY",p:"+598"},
{n:"Uzbekistan",i:"UZ",p:"+998"},
{n:"Vanuatu",i:"VU",p:"+678"},
{n:"Vatican City State (Holy See)",i:"VA",p:"+379"},
{n:"Vatican City State (Holy See)",i:"VA",p:"+39 06 698"},
{n:"Venezuela",i:"VE",p:"+58"},
{n:"Vietnam",i:"VN",p:"+84"},
{n:"Virgin Islands (British)",i:"VG",p:"+1 284"},
{n:"Virgin Islands (US)",i:"VI",p:"+1 340"},
{n:"Wake Island (USA)",i:"US",p:"+1 808"},
{n:"Wallis and Futuna",i:"WF",p:"+681"},
{n:"Yemen",i:"YE",p:"+967"},
{n:"Zambia",i:"ZM",p:"+260"},
{n:"Zanzibar",i:"TZ",p:"+255 24"}, // NO OWN ISO, DISPUTED?
{n:"Zimbabwe",i:"ZW",p:"+263"},
]
