var c=[//n=names,i=ISO -- see countries.js.md for source
{i:"AD",n:"Andorra"},
{i:"AE",n:"United Arab Emirates"},
{i:"AF",n:"Afghanistan"},
{i:"AG",n:"Antigua and Barbuda, Barbuda"},
{i:"AI",n:"Anguilla"},
{i:"AL",n:"Albania"},
{i:"AM",n:"Armenia"},
{i:"AO",n:"Angola"},
{i:"AQ",n:"Australian Antarctic Territory"},
{i:"AR",n:"Argentina"},
{i:"AS",n:"American Samoa"},
{i:"AT",n:"Austria"},
{i:"AU",n:"Australia"},
{i:"AW",n:"Aruba"},
{i:"AX",n:"Åland Islands"},
{i:"AZ",n:"Azerbaijan, Nagorno-Karabakh"},
{i:"BA",n:"Bosnia and Herzegovina"},
{i:"BB",n:"Barbados"},
{i:"BD",n:"Bangladesh"},
{i:"BE",n:"Belgium"},
{i:"BF",n:"Burkina Faso"},
{i:"BG",n:"Bulgaria"},
{i:"BH",n:"Bahrain"},
{i:"BI",n:"Burundi"},
{i:"BJ",n:"Benin"},
{i:"BL",n:"Saint Barthélemy"},
{i:"BM",n:"Bermuda"},
{i:"BN",n:"Brunei Darussalam"},
{i:"BO",n:"Bolivia"},
{i:"BQ",n:"Bonaire, Saba, Sint Eustatius"},
{i:"BR",n:"Brazil"},
{i:"BS",n:"Bahamas"},
{i:"BT",n:"Bhutan"},
{i:"BW",n:"Botswana"},
{i:"BY",n:"Belarus"},
{i:"BZ",n:"Belize"},
{i:"CA",n:"Canada"},
{i:"CC",n:"Cocos (Keeling) Islands"},
{i:"CD",n:"Congo (Democratic Republic of the)"},
{i:"CF",n:"Central African Republic"},
{i:"CG",n:"Congo"},
{i:"CH",n:"Switzerland"},
{i:"CI",n:"Côte d'Ivoire"},
{i:"CK",n:"Cook Islands"},
{i:"CL",n:"Chile, Easter Island"},
{i:"CM",n:"Cameroon"},
{i:"CN",n:"China"},
{i:"CO",n:"Colombia"},
{i:"CR",n:"Costa Rica"},
{i:"CU",n:"Cuba"},
{i:"CV",n:"Cape Verde"},
{i:"CW",n:"Curaçao"},
{i:"CX",n:"Christmas Island"},
{i:"CY",n:"Cyprus, Northern Cyprus"},
{i:"CZ",n:"Czech Republic"},
{i:"DE",n:"Germany"},
{i:"DJ",n:"Djibouti"},
{i:"DK",n:"Denmark"},
{i:"DM",n:"Dominica"},
{i:"DO",n:"Dominican Republic"},
{i:"DZ",n:"Algeria"},
{i:"EC",n:"Ecuador"},
{i:"EE",n:"Estonia"},
{i:"EG",n:"Egypt"},
{i:"ER",n:"Eritrea"},
{i:"ES",n:"Spain"},
{i:"ET",n:"Ethiopia"},
{i:"FI",n:"Finland"},
{i:"FJ",n:"Fiji"},
{i:"FK",n:"Falkland Islands (Malvinas)"},
{i:"FM",n:"Micronesia (Federated States of)"},
{i:"FO",n:"Faroe Islands"},
{i:"FR",n:"France"},
{i:"GA",n:"Gabon"},
{i:"GB",n:"Northern Ireland, United Kingdom"},
{i:"GD",n:"Grenada"},
{i:"GE",n:"Georgia, South Ossetia"},
{i:"GF",n:"French Guiana"},
{i:"GG",n:"Guernsey"},
{i:"GH",n:"Ghana"},
{i:"GI",n:"Gibraltar"},
{i:"GL",n:"Greenland"},
{i:"GM",n:"Gambia"},
{i:"GN",n:"Guinea"},
{i:"GP",n:"Guadeloupe"},
{i:"GQ",n:"Equatorial Guinea"},
{i:"GR",n:"Greece"},
{i:"GS",n:"South Georgia and the South Sandwich Islands"},
{i:"GT",n:"Guatemala"},
{i:"GU",n:"Guam"},
{i:"GW",n:"Guinea-Bissau"},
{i:"GY",n:"Guyana"},
{i:"HK",n:"Hong Kong"},
{i:"HN",n:"Honduras"},
{i:"HR",n:"Croatia"},
{i:"HT",n:"Haiti"},
{i:"HU",n:"Hungary"},
{i:"ID",n:"Indonesia"},
{i:"IE",n:"Ireland"},
{i:"IL",n:"Israel"},
{i:"IM",n:"Isle of Man"},
{i:"IN",n:"India"},
{i:"IO",n:"British Indian Ocean Territory"},
{i:"IQ",n:"Iraq"},
{i:"IR",n:"Iran"},
{i:"IS",n:"Iceland"},
{i:"IT",n:"Italy"},
{i:"JE",n:"Jersey"},
{i:"JM",n:"Jamaica"},
{i:"JO",n:"Jordan"},
{i:"JP",n:"Japan"},
{i:"KE",n:"Kenya"},
{i:"KG",n:"Kyrgyzstan"},
{i:"KH",n:"Cambodia"},
{i:"KI",n:"Kiribati"},
{i:"KM",n:"Comoros"},
{i:"KN",n:"Nevis, Saint Kitts and Nevis"},
{i:"KP",n:"Korea (North)"},
{i:"KR",n:"Korea (South)"},
{i:"KW",n:"Kuwait"},
{i:"KY",n:"Cayman Islands"},
{i:"KZ",n:"Kazakhstan"},
{i:"LA",n:"Laos"},
{i:"LB",n:"Lebanon"},
{i:"LC",n:"Saint Lucia"},
{i:"LI",n:"Liechtenstein"},
{i:"LK",n:"Sri Lanka"},
{i:"LR",n:"Liberia"},
{i:"LS",n:"Lesotho"},
{i:"LT",n:"Lithuania"},
{i:"LU",n:"Luxembourg"},
{i:"LV",n:"Latvia"},
{i:"LY",n:"Libya"},
{i:"MA",n:"Morocco"},
{i:"MC",n:"Monaco"},
{i:"MD",n:"Moldova, Transnistria"},
{i:"ME",n:"Montenegro"},
{i:"MF",n:"Saint Martin (France)"},
{i:"MG",n:"Madagascar"},
{i:"MH",n:"Marshall Islands"},
{i:"MK",n:"North Macedonia"},
{i:"ML",n:"Mali"},
{i:"MM",n:"Myanmar"},
{i:"MN",n:"Mongolia"},
{i:"MO",n:"Macau (Macao)"},
{i:"MP",n:"Northern Mariana Islands"},
{i:"MQ",n:"Martinique"},
{i:"MR",n:"Mauritania"},
{i:"MS",n:"Montserrat"},
{i:"MT",n:"Malta"},
{i:"MU",n:"Mauritius"},
{i:"MV",n:"Maldives"},
{i:"MW",n:"Malawi"},
{i:"MX",n:"Mexico"},
{i:"MY",n:"Malaysia"},
{i:"MZ",n:"Mozambique"},
{i:"NA",n:"Namibia"},
{i:"NC",n:"New Caledonia"},
{i:"NE",n:"Niger"},
{i:"NF",n:"Norfolk Island"},
{i:"NG",n:"Nigeria"},
{i:"NI",n:"Nicaragua"},
{i:"NL",n:"Netherlands"},
{i:"NO",n:"Norway"},
{i:"NP",n:"Nepal"},
{i:"NR",n:"Nauru"},
{i:"NU",n:"Niue"},
{i:"NZ",n:"Chatham Island (New Zealand), New Zealand"},
{i:"OM",n:"Oman"},
{i:"PA",n:"Panama"},
{i:"PE",n:"Peru"},
{i:"PF",n:"French Polynesia"},
{i:"PG",n:"Papua New Guinea"},
{i:"PH",n:"Philippines"},
{i:"PK",n:"Pakistan"},
{i:"PL",n:"Poland"},
{i:"PM",n:"Saint Pierre and Miquelon"},
{i:"PN",n:"Pitcairn Islands"},
{i:"PR",n:"Puerto Rico"},
{i:"PS",n:"Palestine (State of)"},
{i:"PT",n:"Portugal"},
{i:"PW",n:"Palau"},
{i:"PY",n:"Paraguay"},
{i:"QA",n:"Qatar"},
{i:"RE",n:"Réunion"},
{i:"RO",n:"Romania"},
{i:"RS",n:"Serbia"},
{i:"RU",n:"Russia"},
{i:"RW",n:"Rwanda"},
{i:"SA",n:"Saudi Arabia"},
{i:"SB",n:"Solomon Islands"},
{i:"SC",n:"Seychelles"},
{i:"SD",n:"Sudan"},
{i:"SE",n:"Sweden"},
{i:"SG",n:"Singapore"},
{i:"SH",n:"Ascension, Saint Helena, Tristan da Cunha"},
{i:"SI",n:"Slovenia"},
{i:"SJ",n:"Jan Mayen, Svalbard, Taiwan"},
{i:"SK",n:"Slovakia"},
{i:"SL",n:"Sierra Leone"},
{i:"SM",n:"San Marino"},
{i:"SN",n:"Senegal"},
{i:"SO",n:"Somalia"},
{i:"SR",n:"Suriname"},
{i:"SS",n:"South Sudan"},
{i:"ST",n:"São Tomé and Príncipe"},
{i:"SV",n:"El Salvador"},
{i:"SX",n:"Sint Maarten (Netherlands)"},
{i:"SY",n:"Syria"},
{i:"SZ",n:"eSwatini"},
{i:"TC",n:"Turks and Caicos Islands"},
{i:"TD",n:"Chad"},
{i:"TG",n:"Togo"},
{i:"TH",n:"Thailand"},
{i:"TJ",n:"Tajikistan"},
{i:"TK",n:"Tokelau"},
{i:"TL",n:"Timor-Leste"},
{i:"TM",n:"Turkmenistan"},
{i:"TN",n:"Tunisia"},
{i:"TO",n:"Tonga"},
{i:"TR",n:"Turkey"},
{i:"TT",n:"Trinidad and Tobago"},
{i:"TV",n:"Tuvalu"},
{i:"TZ",n:"Tanzania, Zanzibar"},
{i:"UA",n:"Ukraine"},
{i:"UG",n:"Uganda"},
{i:"US",n:"Midway Island (USA), United States, Wake Island (USA)"},
{i:"UY",n:"Uruguay"},
{i:"UZ",n:"Uzbekistan"},
{i:"VA",n:"Vatican City State (Holy See)"},
{i:"VC",n:"Saint Vincent and the Grenadines"},
{i:"VE",n:"Venezuela"},
{i:"VG",n:"Virgin Islands (British)"},
{i:"VI",n:"Virgin Islands (US)"},
{i:"VN",n:"Vietnam"},
{i:"VU",n:"Vanuatu"},
{i:"WF",n:"Wallis and Futuna"},
{i:"WS",n:"Samoa"},
{i:"XK",n:"Kosovo"},
{i:"YE",n:"Yemen"},
{i:"YT",n:"Mayotte"},
{i:"ZA",n:"South Africa"},
{i:"ZM",n:"Zambia"},
{i:"ZW",n:"Zimbabwe"},
]
