CREATE TABLE signed_prekeys (
    id INTEGER PRIMARY KEY ON CONFLICT REPLACE NOT NULL,
    record BLOB NOT NULL
);

CREATE TABLE prekeys (
    id INTEGER PRIMARY KEY ON CONFLICT REPLACE NOT NULL,
    record BLOB NOT NULL
);
