DROP INDEX group_v2_member_recipient_id;
DROP INDEX receipt_recipient_id;
DROP INDEX receipt_message_id;
DROP INDEX group_v1_members_v1_id;
DROP INDEX group_v2_members_v2_id;
DROP INDEX session_group_v1_id;
DROP INDEX session_group_v2_id;
DROP INDEX session_dm_recipient_id;
DROP INDEX attachment_message_id;
