cargo-features = ["strip"]

[package]
name = "whisperfish-traits"
version = "0.6.0-dev"
authors = ["Ruben De Smet <ruben.de.smet@rubdos.be>"]
edition = "2018"
license = "AGPL-3.0-or-later"
description = "Private messaging using Signal for SailfishOS -- traits"

[dependencies]
